export const PRODIAM = {
  legalName: "Prodiam Trading CC",
  website: "https://www.prodiam.co.za/",
  email: "sales@prodiam.co.za",
  phone: "+27 11 334 9010",
  address: "Suite F1W6, The Paragon, 1 Kramer Road, Bedfordview, Johannesburg",
  locationShort: "Bedfordview, Johannesburg",
  valuationWindow: "48-hour",
  settlementWindow: "cleared funds in 72 hours after acceptance",
  appointmentModel: "by appointment",
  yearsInSaTrade: 25,
  foundingYear: 2001,
  businessModel: "direct mine-to-customer manufacturer and dealer",
  manufacturer: true,
  polishingArm: "Procut DCW",
  sisterManufacturer: "D & D Diamonds CC",
  deBeerDbcmCustomerSince: 2019,
  cutSpecialisation: "GIA Ideal Cut",
  kimberleyProcessCompliant: true,
  sadpmrAligned: true,
  ficaCompliant: true,
  typicalPriceVsRetail: "30-40% below retail",
  marketPosition: "direct rough access through De Beers DBCM, in-house polishing at Procut DCW, family business continuity in the same Bedfordview workshop for 25 years",
  specialties: [
    "certified natural diamonds",
    "GIA Ideal Cut diamonds",
    "estate jewellery",
    "loose stones",
    "diamond-ring valuation",
    "signed pieces",
    "broken-set stones",
  ],
  notSpecialties: [
    "bullion desk",
    "watch desk",
    "melt-only scrap-gold buyer",
  ],
  verifiedAgainst: [
    "prodiam.co.za on 2026-05-13",
    "search check on 2026-05-14",
    "prodiam.co.za meta description + diamondguide.co.za live HTML on 2026-05-19",
  ],
  sisterSites: {
    diamondguide: {
      url: "https://diamondguide.co.za/",
      role: "SA diamond authority guide; sister-network editorial site",
    },
  },
} as const;
